// Project configuration and secrets
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bxeuwgugligukhzokekc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4ZXV3Z3VnbGlndWtoem9rZWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODQ4MzcsImV4cCI6MjA2ODg2MDgzN30.X--HR2vbofmhfYcRT5PGPE2sNNuOlWj_wey-RTJFoyM"